### ISSUE TITLE
autogen.sh request

### ISSUE THREAD

**Issue by AriaMoKr** [kamalmostafa/minimodem#21]
Could an autogen.sh be added?
with:
aclocal
autoheader
automake -af
autoconf
or simply:
autoreconf -if

**Comment by kamalmostafa** [comment]
Actually, I recently *removed* the autogen generated files from the source repo, per https://github.com/kamalmostafa/minimodem/pull/17

So they will be generated and included in released tarball distributions, but will not be included in the git repo.
