### ISSUE TITLE
scan-build (clang) detected that ampl_out may contain garbage because it is not initialised (in fsk_frame_analyze)

### ISSUE THREAD

**Issue by ColinIanKing** [kamalmostafa/minimodem#22]
/usr/share/clang/scan-build-3.8/bin/../libexec/ccc-analyzer -DHAVE_CONFIG_H -I. -I..  -D_REENTRANT -I/usr/include/alsa  -Wall  -g -O2 -MT fsk.o -MD -MP -MF .deps/fsk.Tpo -c -o fsk.o fsk.c
fsk.c:493:13: warning: Assigned value is garbage or undefined
            best_a = ampl_out;
                   ^ ~~~~~~~~
1 warning generated.

**Comment by kamalmostafa** [comment]
Fixed by your commit 96a60f51b02fc4ff8eb486fd4e0e763ec8f76bdb.

Thanks Colin!
