### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by AAllport** [kamalmostafa/minimodem#3]
do you plan on porting this to windows 7 and up

**Comment by rjesus-eid** [comment]
I'm not being able to use minimodem for '1200/2100/1300' (baud/mark/space).
Is there an explanation for this?

**Comment by imranrajjad** [comment]
can somebody put up some information on how to compile on Cygwin?

**Comment by nkeck720** [comment]
AFAIK, minimodem uses Pulseaudio, for which no cygwin equivalent is
available. I could be wrong though.

Le lun. 23 avr. 2018 à 6:59 AM, imranrajjad <notifications@github.com> a
écrit :

**Comment by fanfare** [comment]
It runs on Cygwin. 
If you want to build minimodem for Cygwin, find and install the following packages (using Cygwin Setup): `gcc-core`, `pkg-config`, `libgcc1`, `pulseaudio`, `make`, `automake`, `autoconf`, `gawk`, `libsndfile1`, `libsndfile-devel`, `libsndfile-utils`, `libpulse0`, `libpulse-simple0`, `libpulse-devel`, `fftw3`, `libfftw3_3`, `libfftw3-devel`, `libevent2.0_5`

You can now install via
    autoreconf -i
    ./configure --without-alsa
    make
    make install
    
Test:
    echo hello | minimodem --tx 100 -M 1000 -S 3000​

It might give the message: `Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.`

..but run the test again and it will play.

**Comment by rubeemangut** [comment]
> It runs on Cygwin.
> If you want to build minimodem for Cygwin, find and install the following packages (using Cygwin Setup): `gcc-core`, `pkg-config`, `libgcc1`, `pulseaudio`, `make`, `automake`, `autoconf`, `gawk`, `libsndfile1`, `libsndfile-devel`, `libsndfile-utils`, `libpulse0`, `libpulse-simple0`, `libpulse-devel`, `fftw3`, `libfftw3_3`, `libfftw3-devel`, `libevent2.0_5`
> 
> You can now install via
> 
> ```
> autoreconf -i
> ./configure --without-alsa
> make
> make install
> ```
> 
> Test:
> `echo hello | minimodem --tx 100 -M 1000 -S 3000​`
> 
> It might give the message: _Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support._
> 
> ..but run the test again and it will play.

I tried running this project on Cygwin as mentioned above.
While running make it is giving below error:

$ make
make  all-recursive
make[1]: Entering directory '/cygdrive/c/Users/Abhis/OneDrive/Documents/GitHub/minimodem'
Making all in src
make[2]: Entering directory '/cygdrive/c/Users/Abhis/OneDrive/Documents/GitHub/minimodem/src'
gcc -DHAVE_CONFIG_H -I. -I..  -D_REENTRANT   -Wall  -g -O2 -MT simpleaudio-sndio.o -MD -MP -MF .deps/simpleaudio-sndio.Tpo -c -o simpleaudio-sndio.o simpleaudio-sndio.c
simpleaudio-sndio.c:30:10: fatal error: sndio.h: No such file or directory
   30 | #include <sndio.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:466: simpleaudio-sndio.o] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/Abhis/OneDrive/Documents/GitHub/minimodem/src'
make[1]: *** [Makefile:360: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/Abhis/OneDrive/Documents/GitHub/minimodem'
make: *** [Makefile:301: all] Error 2

**Comment by fanfare** [comment]
the software was updated in December and added new dependencies.
try
    ./configure --without-alsa --without-sndio

**Comment by kamalmostafa** [comment]
@fanfare, I'd be amenable to committing your useful cygwin build instructions to the minimodem source as a file called `README.windows` if you'd prepare that and submit a pull request (or just email me directly).

Does `make check` work in the cygwin build?  Assuming so, pls add that after `make`.

**Comment by fanfare** [comment]
Just sent in a PR. Thank you for creating this incredible software.

**Comment by kamalmostafa** [comment]
> Just sent in a PR. Thank you for creating this incredible software.

Merged.  Thank you for contributing to it.

**Comment by chicoze** [comment]
Hello everyone. I can confirm that building in Cygwin does work.

Can I use the .exe created in cygwin to run it from Windows command prompt?
