### ISSUE TITLE
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE

### ISSUE THREAD

**Issue by imranrajjad** [kamalmostafa/minimodem#37]
unable to generate configure script through autoconf -i configure.ac on Ubuntu 16

error

```
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

```

**Comment by nkeck720** [comment]
Why do you need to build from source? On Ubuntu, you can install it in binary form via a `sudo apt install minimodem`.

Sent from Mail for Windows 10

From: imranrajjad
Sent: Monday, April 23, 2018 7:50 AM
To: kamalmostafa/minimodem
Cc: Subscribed
Subject: [kamalmostafa/minimodem] configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE (#37)

unable to generate configure script through autoconf -i configure.ac on Ubuntu 16
error
onfigure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by kamalmostafa** [comment]
Try using `autoreconf -i` (vs. `autoconf -i`).  That'll do the trick!
