### ISSUE TITLE
--binary-raw bug

### ISSUE THREAD

**Issue by increa** [kamalmostafa/minimodem#43]
The command below works fine.  However if I change the 32 to 64, the output is all zeros.  If I change it to 128, the program crashes with "stack smashing detected". 

`minimodem --rx -R 44100 --mark 4000 --space 2000 --binary-raw 32 -f monoshort.wav 500`

**Comment by kamalmostafa** [comment]
Thanks for reporting this.  Its fixed by commit ee881a7:  Works for --binary-raw values <= 64 and yields a sensible error if you try to specify a higher value.
